name: Showcase

on: [push]

permissions:
  contents: write

jobs:
  showcase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/showcase/target
          key: key
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Build Showcase
        working-directory: examples/showcase
        run: trunk build
      - name: Deploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: examples/showcase/dist
          git-config-name: MotBotProg
          git-config-email: dev@modprog.de
          target-folder: /${{ github.ref_name }}/showcase
          clean: true
