name: Showcase

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  showcase:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
            examples/showcase/target
          key: 1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Build Showcase
        working-directory: examples/showcase
        run: trunk build --public-url ${{ github.event.repository.name }}
      - uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'examples/showcase/dist'
      - id: deployment
        uses: actions/deploy-pages@v1
