name: Showcase

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  showcase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
            examples/showcase/target
          key: 1-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Build Showcase
        working-directory: examples/showcase
        run: trunk build --public-url ${{ github.event.repository.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: showcase
          path: examples/showcase/dist
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
            examples/showcase/target
          key: 1-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Generate Docs (reference docs.rs)
        run:  |
          cargo rustdoc -- -Z unstable-options $(cargo metadata --format-version 1 | jq --raw-output '.packages | map("--extern-html-root-url=\(.name)=https://docs.rs/\(.name)/\(.version)") | join(" ")')
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/doc

  deployment:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - showcase
      - docs
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v1
